### ISSUE TITLE
picture size on frontend

### ISSUE THREAD

**Issue by andriineronov** [oda-hub/oda-bot#33]
The .png figure that looks good in the notebook appears truncated in the frontend window. On occasion, here the "y label" of the picture in Gaia orbit-folded lightcurve disappeared (see screenshot below). Is there a way to "fit" the picture in the frontend picture display window?

<img width="1223" alt="PastedGraphic-2" src="https://github.com/oda-hub/oda-bot/assets/27765790/5eb80183-2349-4f4d-bf5b-41ee7b166da5">

**Comment by dsavchenko** [comment]
Could you check that the actual .png created in renku is not truncated. It is a common problem with matplotlib when what you save is not always what you see in nb.

**Comment by andriineronov** [comment]
Sorry, the screenshot was not illustrative. The correct picture (in the notebook on renkulab) is

<img width="437" alt="image" src="https://github.com/oda-hub/oda-bot/assets/27765790/5ad002cc-cbac-45ca-9e66-caf620fe4288">

The picture displayed at the frontend is like this:

<img width="672" alt="image" src="https://github.com/oda-hub/oda-bot/assets/27765790/7d404b95-a9c7-4e96-8fcd-77829b7dadb4">

**Comment by andriineronov** [comment]
It worked, thanks! I added bbox_inches="tight" to plt.savefig, to get the png image right.

**Comment by andriineronov** [comment]
that was fast
