### ISSUE TITLE
a config to make an instrument public?

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/oda-bot#58]
can we make at least a site-wide config (env variable?) to make an instrument public?

**Comment by volodymyrss** [comment]
eh, so how do we actually make it public?

**Comment by dsavchenko** [comment]
This is a side-wide config for a moment, so that if you set `default_creative_status = "production"`, every instrument deployed on this site will be public

There is a bug in the plugin when processing status change on-the-fly and corresponding fix https://github.com/oda-hub/dispatcher-plugin-nb2workflow/pull/99 is waitin for review

**Comment by volodymyrss** [comment]
> This is a side-wide config for a moment, so that if you set `default_creative_status = "production"`, every instrument deployed on this site will be public

That I get, but it also tries to read `workflow_status` from `project` and it's never there, right?

Would be best to real it from something, maybe like `live-workflow-public` topic for example (this would be easy I suppose)?

> 
> There is a bug in the plugin when processing status change on-the-fly and corresponding fix [oda-hub/dispatcher-plugin-nb2workflow#99](https://github.com/oda-hub/dispatcher-plugin-nb2workflow/pull/99) is waitin for review

**Comment by dsavchenko** [comment]
> That I get, but it also tries to read `workflow_status` from `project` and it's never there, right?

Which place in code you are reffering to? It can't be there, `project` is a gitlab response.



> Would be best to real it from something, maybe like `live-workflow-public` topic for example (this would be easy I suppose)?

Yes, this is very straightforward change. The solution is not ideal, but let's stick to it for now https://github.com/oda-hub/oda-bot/pull/61

**Comment by volodymyrss** [comment]
> > That I get, but it also tries to read `workflow_status` from `project` and it's never there, right?
> 
> Which place in code you are reffering to? 

there 

https://github.com/oda-hub/oda-bot/blob/559b79318d8fa35671dc2c12b3e12c0f2b7c2433/odabot/cli.py#L583

> It can't be there, `project` is a gitlab response.

it's mutable, it could have been assigned something

> 
> > Would be best to real it from something, maybe like `live-workflow-public` topic for example (this would be easy I suppose)?
> 
> Yes, this is very straightforward change. The solution is not ideal, but let's stick to it for now #61
