### ISSUE TITLE
can galaxy bot also put entires in gitlab CI ?

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/oda-bot#81]
@Andrei-EPFL likes the CI reports for MMODA but lacks the reports for Galaxy bot. Would it be dfficult to add them?

**Comment by dsavchenko** [comment]
It's not very difficult. I didn't add it because contrary to MMODA bot, the Galaxy one creates a PR in the github repo, which acts as a report.
But it may still be good to have it, I agree

**Comment by volodymyrss** [comment]
> It's not very difficult. I didn't add it because contrary to MMODA bot, the Galaxy one creates a PR in the github repo, which acts as a report.

That's what I thought too, but people like it in gitlab even better. 

> But it may still be good to have it, I agree

In fact the job might have a link to the github PR. Maybe some comment about adding tag in the PR too. Doc is one thing, but the UI should be smooth and instructive.

**Comment by Andrei-EPFL** [comment]
ok now I see what you mean by the report in PR. and also that there is a commits tab where you can see the newest commits, I did not see this before. thanks!

**Comment by volodymyrss** [comment]
> ok now I see what you mean by the report in PR. and also that there is a commits tab where you can see the newest commits, I did not see this before. thanks!

You are not the first one to ask this. Also even I keep navigating manually from gitlab workflow repo to github PR. The change @dsavchenko would make is rather small and very useful.

**Comment by dsavchenko** [comment]
The PR branch is deployed as staging bot. Let's test it manually than merge if it's ok
